version: "2"

volumes:
  blog_data:
    external: true

networks:
  web:
    external:
      name: proxy_webgateway

services:
  db:
    image: postgres:9.6.1
    env_file: .env.prod
    networks:
      - web
    volumes:
      - blog_data:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env.prod
    environment:
      HANAMI_ENV: production
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:example.keiththomps.com"
      - "traefik.port=$PORT"
    command: script/run
    ports:
      - "$PORT"
    depends_on:
      - db
