#!/bin/bash -e

# This script should be run outside of a container

function docker_command {
  # Use 'sudo' if running on Jenkins
  if [[ $(whoami) == "jenkins" ]]; then
    sudo docker-compose -f docker-compose.ci.yml $*
  else
    docker-compose -f docker-compose.ci.yml $*
  fi
}

function finish {
  docker_command stop
  docker_command rm -fv
}

trap finish EXIT

docker_command up -d test_db
sleep 5
docker_command build ci
docker_command run --rm ci
